### ISSUE TITLE
Setting an x and y offset when cropping

### ISSUE THREAD

**Issue by JosephShering** [gavinbunney/Toucan#11]
Is there a way I can crop out an x, y, width and height from an image?

**Comment by gavinbunney** [comment]
I assume you are trying to say, crop out the middle of the image?

Thanks to this awesome pull request by @waterskier2007 - you now can specify a `UIBezierPath` to mask out the image... https://github.com/gavinbunney/Toucan#path-mask

Would just be a case of changing together a `maskWithPage` then a `resize` as required.
