### ISSUE TITLE
0.4.x versions get compile error in Xcode 6.4 

### ISSUE THREAD

**Issue by chenyuan** [gavinbunney/Toucan#15]
hi can you help me with this?
<img width="1107" alt="screen shot 2015-08-15 at 10 14 59 am" src="https://cloud.githubusercontent.com/assets/334233/9286423/9056db8c-4336-11e5-8084-dd4400fa52bb.png">

downgrading to 0.3.x solves the issue

```swift
/// 0.3.x code
            let context : CGContextRef = CGBitmapContextCreate(nil, CGImageGetWidth(image.CGImage), CGImageGetWidth(image.CGImage),
                CGImageGetBitsPerComponent(image.CGImage),
                CGImageGetBytesPerRow(image.CGImage),
                CGImageGetColorSpace(image.CGImage),
                CGImageGetBitmapInfo(image.CGImage))!;
```

**Comment by gavinbunney** [comment]
Yep that's correct - from v0.4.x only Swift2/Xxode 7 is supported since Apple has changed a lot of the APIs to be more friendly; the latest v0.3.x should work for you though.
