### ISSUE TITLE
Tag stable releases ( Carthage support )

### ISSUE THREAD

**Issue by s-aska** [gavinbunney/Toucan#2]
If stick a tag such as 1.0.0 or 0.0.1, can correspond to [Carthage](https://github.com/Carthage/Carthage#tag-stable-releases).

```bash
carthage update
*** Fetching Toucan
*** Checking out Toucan at "0.0.1"
*** Building scheme "Toucan" in Toucan.xcworkspace
```

:smile:

**Comment by gavinbunney** [comment]
Done :+1: 

https://github.com/gavinbunney/Toucan/tree/v0.1.0
