### ISSUE TITLE
Border width sharpness

### ISSUE THREAD

**Issue by Vaberer** [gavinbunney/Toucan#21]
Hello, I am just using this library and I see a little imperfection in the border even when I use it as a rounded image or with corner radius. It isn't as sharp as I expect. So if you look closely into the border you will see that it isn't a beautiful border shape.

What could by wrong?

Thanks

Patrik

**Comment by gavinbunney** [comment]
Is the source image retina quality? The image code handles retina images quite well - no noticeable edge imperfections, but non-retina images aren't quite as sharp (obviously).

Feel free to reopen the issue with a sample I can take a look at... thanks!
