### ISSUE TITLE
How can i achieve UIViewContentMode.ScaleAspectFit

### ISSUE THREAD

**Issue by nishantdongare** [gavinbunney/Toucan#23]
I want to achieve ScaleAspectFit in toucan. Is it possible.

**Comment by gavinbunney** [comment]
Sure is - You need to set the fit mode to `Clip`:

e.g.
`Toucan(image: portraitImage).resize(CGSize(width: 500, height: 500), fitMode: Toucan.Resize.FitMode.Clip).image`
