### ISSUE TITLE
How can I get the Toucan framework?

### ISSUE THREAD

**Issue by akring** [gavinbunney/Toucan#26]
I found that Toucan framework is not in zip file,so I tried to build and archive the Toucan project.
Finally I got a Toucan.framework,but I found the header file just include:

```
#import <UIKit/UIKit.h>

//! Project version number for Toucan.
FOUNDATION_EXPORT double ToucanVersionNumber;

//! Project version string for Toucan.
FOUNDATION_EXPORT const unsigned char ToucanVersionString[];
```

Is anything I did wrong?

**Comment by krunalbhavsar** [comment]
I've been facing same issue that akring has.

**Comment by akring** [comment]
I installed that via cocoapod and problem solved...Just try it:|

**Comment by krunalbhavsar** [comment]
thenx..
