### ISSUE TITLE
How to crop from top left

### ISSUE THREAD

**Issue by noctivityinc** [gavinbunney/Toucan#28]
When using resize and crop mode, it appears to crop the image from the middle.  How can we crop from the top left corner?  For example, if I have a UIImageView that is 400 x 200 and I want the image to be 400 width but crop anything over 200 high so just the top 200 pixels are visible, how can I do that?

**Comment by dp4dileep** [comment]
I don't know is this right method or not but you can change value of x and y on line number 175 in Toucan.swift. For top left , set x and y 0.

**Comment by gavinbunney** [comment]
Hi @noctivityinc - best to use a path mask for that: https://github.com/gavinbunney/Toucan#path-mask
