### ISSUE TITLE
Move Objective-C helper methods to extension?

### ISSUE THREAD

**Issue by stephencelis** [gavinbunney/Toucan#3]
This library is really well-composed! I did notice that the Objective-C helper functions are peppered, throughout, though. Moving them to an extension (that is scoped by a build parameter or that loads in a CocoaPod subspec) would make it easy for pure Swift apps to disable the redundancy.

**Comment by gavinbunney** [comment]
Thanks Stephen - good idea :dango:

**Comment by natan** [comment]
Toucan no longer uses any Objective-C helper methods AFAIK. This should be closed?
