### ISSUE TITLE
Clip and Scale fitmodes do the same

### ISSUE THREAD

**Issue by Casporro** [gavinbunney/Toucan#34]
Why the fitmodes Clip and Scale get the same result??

**Comment by DrewKiino** [comment]
same

**Comment by gavinbunney** [comment]
Hi @DrewKiino , @Casporro , do you have a sample image I can take a look with?

**Comment by fraserscottmorrison** [comment]
I was about to report a bug with .clip, but its probably the same issue raised here

If I have an image that is 800x1100  and I tell Toucan to clip it to 1200x1200, I was expecting to get an image that was 872x1200 (the maximum dimension is 1200), but I actually get an image thats 1200x1650 (the minimum dimension is 122)

I fixed this in resizeImage with the following

```
public static func resizeImage(_ image: UIImage, size: CGSize, fitMode: FitMode = .clip) -> UIImage {

    ...
    let scaleRatio = fitMode == .clip ? min(heightRatio, widthRatio) : max(heightRatio, widthRatio)
    ...
}
```

**Comment by fraserscottmorrison** [comment]
Actually, the FitMode enum could be named to better to mirror UIImageView.contentMode

.crop is should stay as .crop

But 
.scale is .scaleToFill
.clip is currently .scaleAspectFill  but I think it should be .scaleAspectFit

Maybe you should have both

**Comment by philippeauriach** [comment]
Proposed a PR using @fraserscottmorrison solution which works great for solving clipping ratio.
