### ISSUE TITLE
pod problem

### ISSUE THREAD

**Issue by ira-ira** [gavinbunney/Toucan#35]
Hi!
I'm trying to install pod by " pod 'Toucan' "
but I got 'Unable to find a specification for `Toucan` '
Could you tell what exactly should I write in pod file?
Thanks

**Comment by wilsonbalderrama** [comment]
I used the below Podfile:

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Toucan'

**Comment by gavinbunney** [comment]
The Toucan podspec can be viewed here: https://cocoapods.org/pods/Toucan

Closing this issue as it's quite old (and cocoapods has changed a lot of the swift support issues) - let me know if you're still having problems.
