### ISSUE TITLE
cannot import Toucan

### ISSUE THREAD

**Issue by hieuvo** [gavinbunney/Toucan#36]
add Toucan to podfile, `pod install` runs well, and there isn't any error, but I cannot import Toucan library

![screenshot](http://i.imgur.com/mNwuXDR.png)

**Comment by DanShevlyuk** [comment]
@hieuvo did you build you project before importing?

**Comment by GadgetAddict** [comment]
I cannot add it to my pod file b/c it says the pod name is wrong-  and nowhere in the docs do you say what the POD NAME would be

**Comment by gavinbunney** [comment]
The Toucan podspec can be viewed here: https://cocoapods.org/pods/Toucan

Closing this issue as it's quite old - let me know if you're still having problems.
