### ISSUE TITLE
Update to Swift 3.0

### ISSUE THREAD

**Issue by scottdelly** [gavinbunney/Toucan#37]
Happy to provide a PR if it'll help

**Comment by troypayne** [comment]
@scottdelly Maybe fork and I can point to your repo until an official Swift 3 branch

**Comment by kean** [comment]
@gavinbunney, any updates on this one? I'd like to integrate Toucan in [Nuke](https://github.com/kean/Nuke). I could submit a PR with Swift 3 support.

**Comment by nahlam** [comment]
any updates?

**Comment by kean** [comment]
I made a PR with Swift 3 migration. And here's [a fork](https://github.com/kean/Toucan/tree/swift3) (see `swift3` branch) which you can use until main Toucan repo is updated.

Also check out [new Toucan plugin](https://github.com/kean/Nuke-Toucan-Plugin) for Nuke ⚡

**Comment by fernandolicon** [comment]
Great! Thanks @kean, hope the main repo gets it update soon.

**Comment by gavinbunney** [comment]
v0.6 has been release with swift-3 support! Thanks @kean
