### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pjebs** [gavinbunney/Toucan#46]
My app keeps crashing at this point when I try to resize an image and add a corner radius mask:

The crash occurs at this point:

```
        static func drawImageWithClosure(size size: CGSize!, closure: (size: CGSize, context: CGContext) -> ()) -> UIImage {
            UIGraphicsBeginImageContextWithOptions(size, false, 0)
            closure(size: size, context: UIGraphicsGetCurrentContext()!)
            let image : UIImage = UIGraphicsGetImageFromCurrentImageContext()
            UIGraphicsEndImageContext()
            return image
        }
```

UIGraphicsGetCurrentContext()! ==> fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by gavinbunney** [comment]
Hi @pjebs, can you provide your calling code? Could be where you are calling it from (it doesn't have a graphics context), or it could be prematurely closed.

**Comment by pjebs** [comment]
The crash only occurred in rare situations and I found it to be unpredictable when it was going to happen.

For my purposes I've actually stopped using your library for the bit that was causing the crash.

```
UIImage *curve;

//Original code
curve = [[[[Toucan alloc] initWithImage:fingerImage] resizeByScaling:CGSizeMake(64, self.btnPhotoheight.constant)] maskWithRoundedRectWithCornerRadius:8 borderWidth:1 borderColor:[UIColor colorWithRed:218/255.0 green:19/255.0 blue:118/255.0 alpha:1]].image;

//My workaround due to occasional crash
curve = fingerImage;
    self.btnPhoto.layer.cornerRadius = 8;
    self.btnPhoto.layer.borderWidth = 1;
    self.btnPhoto.layer.borderColor = [UIColor colorWithRed:218/255.0 green:19/255.0 blue:118/255.0 alpha:1].CGColor;
    self.btnPhoto.layer.masksToBounds = YES;
    
    [[self.btnPhoto imageView] setContentMode: UIViewContentModeScaleAspectFit];
    [self.btnPhoto setImage:curve forState:UIControlStateNormal];
    [self.btnPhoto setImage:curve forState:UIControlStateSelected];
    [self.btnPhoto setImage:curve forState:UIControlStateHighlighted];
```

**Comment by pjebs** [comment]
Perhaps just check if `UIGraphicsGetCurrentContext()` is nill before attempting to unwrap it.
If your library is bug-free, then it would have no effect. If it isn't, then at least the app won't crash even if the library doesn't return an expected UIImage.

**Comment by otymartin** [comment]
@gavinbunney 
This error happens unpredicatbley in my collectionview when scrolling.

**Comment by Appsido** [comment]
Same problem here while scrolling in table view. The problem is due to force unwrap UIGraphicsGetCurrentContext() in static func drawImageWithClosure method
