### ISSUE TITLE
resizeByScaling not working

### ISSUE THREAD

**Issue by pjebs** [gavinbunney/Toucan#47]
I have the same code which I use on iPad mini 1 and iPhone 6.
The code takes photo by camera and then applies `resizeByScaling:CGSizeMake(128, 128)`.

For iPad mini 1: it correctly resizes the image to 128x128.
On iPhone 6, it is 256x256.

I think there is something wrong with the function. Perhaps it doesn't factor in retina level????

**Comment by gavinbunney** [comment]
Hi @pjebs, how are you checking the size of the image? Retina images are always stored at 2x, but if you query their size they will correctly return the non-retina resolution.

**Comment by pjebs** [comment]
The issue is when you convert the UIImage using `UIImageJPEGRepresentation`. The `NSData` when converted back to `UIImage` is double size and not the same as original.

I've worked around it because I know what size it should be. For others, they may not.

Close the issue if you wish. Thanks for the library.

**Comment by fraserscottmorrison** [comment]
I just encountered whats probably the same problem. The image Im resizing has a scale of 1, but drawImageWithClosure will use scale equal to UIScreen.main.scale which is in most cases 2.

I fixed this by modifying the func to use the same scale at the image

I'll submit a PR

`        static func drawImageWithClosure(size: CGSize!, scale: CGFloat = 0, closure: (_ size: CGSize, _ context: CGContext) -> ()) -> UIImage {
            UIGraphicsBeginImageContextWithOptions(size, false, scale)
            closure(size, UIGraphicsGetCurrentContext()!)
            let image : UIImage = UIGraphicsGetImageFromCurrentImageContext()!
            UIGraphicsEndImageContext()
            return image
        }
`

**Comment by gavinbunney** [comment]
Issue fixed by @fraserscottmorrison's PR.
