### ISSUE TITLE
any plan to support swift4？

### ISSUE THREAD

**Issue by Mosaics** [gavinbunney/Toucan#59]

**Comment by ThoseGuysInTown** [comment]
For real... Hope it's soon. Do you @Mosaics know of any alternatives?

**Comment by supersimple** [comment]
perhaps someone here should start a fork or maybe take over this project. It doesnt look like it is being updated/maintained any more.

**Comment by yar1vn** [comment]
pull request submitted. waiting for it to be merged.

**Comment by gavinbunney** [comment]
Toucan v0.7+ now supports Swift4
