### ISSUE TITLE
Use of unresolved identifier 'Toucan'

### ISSUE THREAD

**Issue by Ctech83** [gavinbunney/Toucan#65]
Hi, 

Im using Xcode 9.2 and Swift 4. I've tested both Toucan 1.0.0 and 0.7, Im getting the error "use of unresolved identifier 'Toucan' anyway I try to use the framework... Im I doing something wrong, or is this a bug?

**Comment by gavinbunney** [comment]
Generally this is a linking error (Toucan v1.1.0 released today works with both Xcode v10 and Swift 4.0+4.2). For specifics around linking, you're best bet is somewhere like stackoverflow: https://stackoverflow.com/questions/42843054/how-to-include-a-library-into-my-swift-project
