### ISSUE TITLE
Unable to compile Toucan (installed via Cocoapods) once main project has migrated to Swift 4.2

### ISSUE THREAD

**Issue by MattCarr147** [gavinbunney/Toucan#70]
Not sure what the desired way to resolve this would be:

- The current podspec could be updated, with the `spec.swift_version` property set to '4.0'
- Wait until Swift 4.2 has been released fully and migrate Toucan accordingly.

In either case, setting the swift_version in the podspec would be a good idea to avoid this sort of thing in the future. 

Note that the migrations for Toucan are (so far) very simple, just several instances of 

> `UIImageOrientation` has been renamed to `UIImage.Orientation`.

**Comment by muhrifqii** [comment]
Add this to the end of Podfile might help

```ruby

post_install do | installer |
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if ['Toucan'].include? target.name
                config.build_settings['SWIFT_VERSION'] = '4.0'
                else
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end


```

**Comment by OlivierVoyer** [comment]
Any estimate for a new 4.2 release?
I am using the pod as a dependency in my podspec so I cannot use the post_install trick.
Xcode automatic migration is probably enough to migrate your side.
Thanks in advance

**Comment by muhrifqii** [comment]
there's already a PR for it #71 and still open. cc: @gavinbunney

**Comment by gavinbunney** [comment]
v1.1.0 of Toucan is now compatible with both Swift 4.0 and 4.2
