### ISSUE TITLE
Support for Xcode 7 and Swift 2.0

### ISSUE THREAD

**Issue by HerbstLukas** [gavinbunney/Toucan#9]
Are you working on an update? :) 
would be awesome!

**Comment by gavinbunney** [comment]
Absolutely :+1: 

In the meantime, if you run Toucan through the Swift upgrader, it fixes up the new markdown comments and few little places in the code...  should be good to go.

![jz1vm8q jpg](https://cloud.githubusercontent.com/assets/409207/8298497/df33cfc0-19ac-11e5-8ccb-1fed599560a4.gif)

**Comment by gavinbunney** [comment]
Swift 2 now support in version 0.2.1 :santa:
